name: Manual workflow [MacOS Monterey]
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  vm-job:
# https://github.com/actions/virtual-environments/blob/macOS-12/20220516.1/images/macos/macos-12-Readme.md
    runs-on: macos-12 # Monterey
    services:
      nginx:
        image: nginx:latest

    steps:
    - uses: actions/checkout@v2
    - name: System fingerprint
      run: |
        printf "My current shell - %s\n" "$SHELL"
        uname -a
        sysctl -a | grep machdep.cpu

#  Already installed  
#   - name: Installing homebrew
#     run: /bin/bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Installing docker via brew
      run: brew install docker

    - name: Wget test
      run: wget -O - http://localhost/

    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  
  container-job:
    needs: vm-job
    runs-on: macos-12 # Monterey 
    container: ubuntu:22.04
    services:
      nginx:
        image: nginx:latest
    steps:
      - uses: actions/checkout@v2
      - name: System fingerprint
        run: |
          printf "My current shell - %s\n" "$SHELL"
          uname -a
          cat /proc/cpuinfo

      - name: Install docker client
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update && apt-get install curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Run service container
        run: docker run --rm --detach --network ${{ job.container.network }} --name nginx2 nginx:latest

      - name: run wget in Docker container
        run: |
          docker run --rm --network ${{ job.container.network }} alpine:3.15 wget -O - http://nginx/
          docker run --rm --network ${{ job.container.network }} alpine:3.15 wget -O - http://nginx2/

      - name: Show running containers
        run: docker ps

      - name: Inspect service container
        run: docker inspect ${{ job.services.nginx.id }}

      - name: Stop nginx2 container
        if: always()
        run: docker stop nginx2
    
   
