name: Manual workflow [MacOS Monterey]
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  vm-job:
    runs-on: macos-12 # Monterey
    steps:

    - name: System fingerprint
      run: |
        printf "My current shell - %s\n" "$SHELL"
        uname -a
        sysctl -a | grep machdep.cpu

    - name: Installing homebrew
      run: /bin/bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Installing docker via brew
      run: brew install --cask docker

    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
  
  container-job:
    runs-on: macos-12 # Monterey
    container: alpine:3.14
    steps:
    
    - name: Run in container
      run: |
          echo "This job does specify a container."
          echo "It runs in the container instead of the VM."
          echo "Hello ${{ github.event.inputs.name }}"
