name: Manual workflow [MacOS Monterey]
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: macos-12 # Monterey
    steps:

    - name: System fingerprint
      run: |
        printf "My current shell - %s\n" "$SHELL"
        uname -a
        sysctl -a | grep machdep.cpu

    - name: Installing homebrew
      run: /bin/bash -c "NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Installing docker via brew
      run: brew install docker

# --- https://github.com/marketplace/actions/docker-run-action
    - name: Checkout 
      uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
    - uses: addnab/docker-run-action@v3
      with:
 #       username: ${{ secrets.DOCKER_USERNAME }}
 #       password: ${{ secrets.DOCKER_PASSWORD }}
 #       registry: gcr.io
        image: alpine:latest
        options: -v ${{ github.workspace }}:/work -e NAME=${{ github.event.inputs.name }}"
        run: |
          echo "Running from alpine container..."
          echo "Alpine: Hello ${NAME}"
# -----------------------------------------------------------
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"